name: portfolio
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  blobs: ^2.0.0
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_next: ^0.1.0
  font_awesome_flutter: ^9.1.0
  get_it: ^7.2.0
  go_router: null
  http: ^0.13.4
  logger: null
  stacked: ^2.2.7
  stacked_services: ^0.8.15
  url_launcher: ^6.0.12

dev_dependencies:
  build_runner: null
  change_app_package_name: null
  flutter_lints: null
  flutter_test:
    sdk: flutter
  stacked_generator: null
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
