name: portfolio
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_next:
    git:
      url: https://github.com/shashiben/flutter_next.git
  flutter_svg: ^1.1.4
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  logger: ^1.1.0
  scrollable_positioned_list: ^0.3.4
  stacked: ^3.0.0
  stacked_services: ^0.9.5

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.8.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/company/
    - assets/images/projects/
    - assets/images/skill/
