name: portfolio
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  #*Icons
  cupertino_icons: ^1.0.3
  flutter_icons: ^1.1.0
  font_awesome_flutter: ^10.3.0

  #*Architecture
  stacked: ^3.0.1
  stacked_services: ^0.9.8
  responsive_builder: ^0.4.1
  get_it: ^7.2.0
  injectable: ^2.1.0
  flutter_hooks: ^0.18.0
  url_strategy: ^0.2.0

  #*Services
  url_launcher: ^6.0.12
  http: ^0.13.4

  #*Utilities
  collapsible_sidebar: ^2.0.1+2
  animated_text_kit: ^4.2.1
  simple_animations: ^5.0.0+3
  oktoast: ^3.1.3+1
  flutter_neumorphic: ^3.2.0
  animations: ^2.0.1
  carousel_slider: ^4.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  injectable_generator: ^2.1.3
  auto_route_generator: ^5.0.3
  build_runner: ^2.1.4
  change_app_package_name: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
