// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjW8vmSBC0h1O-PtkayCv2v_YvugZXO0E',
    appId: '1:527453052231:web:a86f6ba25f8f6af59a0062',
    messagingSenderId: '527453052231',
    projectId: 'portfolio-92859',
    authDomain: 'portfolio-92859.firebaseapp.com',
    storageBucket: 'portfolio-92859.appspot.com',
    measurementId: 'G-H9FWM08RLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0_aoEdLDzKDiShAyyTRDPncdUiovbOPQ',
    appId: '1:527453052231:android:2e77aa403677dbe09a0062',
    messagingSenderId: '527453052231',
    projectId: 'portfolio-92859',
    storageBucket: 'portfolio-92859.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0T9uT5a2N6yT0DvXr8Ej5gKNLR0gVmMw',
    appId: '1:527453052231:ios:4f7ca9b97f6989ed9a0062',
    messagingSenderId: '527453052231',
    projectId: 'portfolio-92859',
    storageBucket: 'portfolio-92859.appspot.com',
    iosClientId: '527453052231-4u14qk6r4latruulkbotvmiq79fgda7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0T9uT5a2N6yT0DvXr8Ej5gKNLR0gVmMw',
    appId: '1:527453052231:ios:4f7ca9b97f6989ed9a0062',
    messagingSenderId: '527453052231',
    projectId: 'portfolio-92859',
    storageBucket: 'portfolio-92859.appspot.com',
    iosClientId: '527453052231-4u14qk6r4latruulkbotvmiq79fgda7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );
}
